# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugId', models.SlugField(unique=True)),
                ('data', models.TextField()),
                ('lang', models.CharField(choices=[('RAW', 'Plain-Text'), ('TEX', 'latex'), ('PY', 'python-code'), ('C', 'C-code')], default='RAW', max_length=10)),
            ],
        ),
    ]
