# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textin',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
